// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: proto/ledger/v1/ledger.proto

package ledgerv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Money represents 128-bit unsigned integer money amount using two uint64 fields.
type Money struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Lo            uint64                 `protobuf:"varint,1,opt,name=lo,proto3" json:"lo,omitempty"`
	Hi            uint64                 `protobuf:"varint,2,opt,name=hi,proto3" json:"hi,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Money) Reset() {
	*x = Money{}
	mi := &file_proto_ledger_v1_ledger_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Money) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Money) ProtoMessage() {}

func (x *Money) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ledger_v1_ledger_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Money.ProtoReflect.Descriptor instead.
func (*Money) Descriptor() ([]byte, []int) {
	return file_proto_ledger_v1_ledger_proto_rawDescGZIP(), []int{0}
}

func (x *Money) GetLo() uint64 {
	if x != nil {
		return x.Lo
	}
	return 0
}

func (x *Money) GetHi() uint64 {
	if x != nil {
		return x.Hi
	}
	return 0
}

type Account struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Id               []byte                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Currency         string                 `protobuf:"bytes,2,opt,name=currency,proto3" json:"currency,omitempty"`
	PostedDebits     *Money                 `protobuf:"bytes,3,opt,name=posted_debits,json=postedDebits,proto3" json:"posted_debits,omitempty"`
	PostedCredits    *Money                 `protobuf:"bytes,4,opt,name=posted_credits,json=postedCredits,proto3" json:"posted_credits,omitempty"`
	PendingDebits    *Money                 `protobuf:"bytes,5,opt,name=pending_debits,json=pendingDebits,proto3" json:"pending_debits,omitempty"`
	PendingCredits   *Money                 `protobuf:"bytes,6,opt,name=pending_credits,json=pendingCredits,proto3" json:"pending_credits,omitempty"`
	Balance          *Money                 `protobuf:"bytes,7,opt,name=balance,proto3" json:"balance,omitempty"`
	AvailableBalance *Money                 `protobuf:"bytes,8,opt,name=available_balance,json=availableBalance,proto3" json:"available_balance,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *Account) Reset() {
	*x = Account{}
	mi := &file_proto_ledger_v1_ledger_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Account) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Account) ProtoMessage() {}

func (x *Account) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ledger_v1_ledger_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Account.ProtoReflect.Descriptor instead.
func (*Account) Descriptor() ([]byte, []int) {
	return file_proto_ledger_v1_ledger_proto_rawDescGZIP(), []int{1}
}

func (x *Account) GetId() []byte {
	if x != nil {
		return x.Id
	}
	return nil
}

func (x *Account) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *Account) GetPostedDebits() *Money {
	if x != nil {
		return x.PostedDebits
	}
	return nil
}

func (x *Account) GetPostedCredits() *Money {
	if x != nil {
		return x.PostedCredits
	}
	return nil
}

func (x *Account) GetPendingDebits() *Money {
	if x != nil {
		return x.PendingDebits
	}
	return nil
}

func (x *Account) GetPendingCredits() *Money {
	if x != nil {
		return x.PendingCredits
	}
	return nil
}

func (x *Account) GetBalance() *Money {
	if x != nil {
		return x.Balance
	}
	return nil
}

func (x *Account) GetAvailableBalance() *Money {
	if x != nil {
		return x.AvailableBalance
	}
	return nil
}

type Transfer struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Id              []byte                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	DebitAccountId  []byte                 `protobuf:"bytes,2,opt,name=debit_account_id,json=debitAccountId,proto3" json:"debit_account_id,omitempty"`
	CreditAccountId []byte                 `protobuf:"bytes,3,opt,name=credit_account_id,json=creditAccountId,proto3" json:"credit_account_id,omitempty"`
	Amount          *Money                 `protobuf:"bytes,4,opt,name=amount,proto3" json:"amount,omitempty"`
	IdempotencyKey  []byte                 `protobuf:"bytes,5,opt,name=idempotency_key,json=idempotencyKey,proto3" json:"idempotency_key,omitempty"`
	CreatedAt       int64                  `protobuf:"varint,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	Flags           uint32                 `protobuf:"varint,7,opt,name=flags,proto3" json:"flags,omitempty"`
	Timeout         uint64                 `protobuf:"varint,8,opt,name=timeout,proto3" json:"timeout,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Transfer) Reset() {
	*x = Transfer{}
	mi := &file_proto_ledger_v1_ledger_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Transfer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Transfer) ProtoMessage() {}

func (x *Transfer) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ledger_v1_ledger_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Transfer.ProtoReflect.Descriptor instead.
func (*Transfer) Descriptor() ([]byte, []int) {
	return file_proto_ledger_v1_ledger_proto_rawDescGZIP(), []int{2}
}

func (x *Transfer) GetId() []byte {
	if x != nil {
		return x.Id
	}
	return nil
}

func (x *Transfer) GetDebitAccountId() []byte {
	if x != nil {
		return x.DebitAccountId
	}
	return nil
}

func (x *Transfer) GetCreditAccountId() []byte {
	if x != nil {
		return x.CreditAccountId
	}
	return nil
}

func (x *Transfer) GetAmount() *Money {
	if x != nil {
		return x.Amount
	}
	return nil
}

func (x *Transfer) GetIdempotencyKey() []byte {
	if x != nil {
		return x.IdempotencyKey
	}
	return nil
}

func (x *Transfer) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *Transfer) GetFlags() uint32 {
	if x != nil {
		return x.Flags
	}
	return 0
}

func (x *Transfer) GetTimeout() uint64 {
	if x != nil {
		return x.Timeout
	}
	return 0
}

type CreateAccountRequest struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	Id                   []byte                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Currency             string                 `protobuf:"bytes,2,opt,name=currency,proto3" json:"currency,omitempty"`
	InitialPostedCredits *Money                 `protobuf:"bytes,3,opt,name=initial_posted_credits,json=initialPostedCredits,proto3" json:"initial_posted_credits,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *CreateAccountRequest) Reset() {
	*x = CreateAccountRequest{}
	mi := &file_proto_ledger_v1_ledger_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateAccountRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAccountRequest) ProtoMessage() {}

func (x *CreateAccountRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ledger_v1_ledger_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAccountRequest.ProtoReflect.Descriptor instead.
func (*CreateAccountRequest) Descriptor() ([]byte, []int) {
	return file_proto_ledger_v1_ledger_proto_rawDescGZIP(), []int{3}
}

func (x *CreateAccountRequest) GetId() []byte {
	if x != nil {
		return x.Id
	}
	return nil
}

func (x *CreateAccountRequest) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *CreateAccountRequest) GetInitialPostedCredits() *Money {
	if x != nil {
		return x.InitialPostedCredits
	}
	return nil
}

type CreateAccountResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Account       *Account               `protobuf:"bytes,1,opt,name=account,proto3" json:"account,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateAccountResponse) Reset() {
	*x = CreateAccountResponse{}
	mi := &file_proto_ledger_v1_ledger_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateAccountResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAccountResponse) ProtoMessage() {}

func (x *CreateAccountResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ledger_v1_ledger_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAccountResponse.ProtoReflect.Descriptor instead.
func (*CreateAccountResponse) Descriptor() ([]byte, []int) {
	return file_proto_ledger_v1_ledger_proto_rawDescGZIP(), []int{4}
}

func (x *CreateAccountResponse) GetAccount() *Account {
	if x != nil {
		return x.Account
	}
	return nil
}

type GetAccountRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            []byte                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAccountRequest) Reset() {
	*x = GetAccountRequest{}
	mi := &file_proto_ledger_v1_ledger_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAccountRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAccountRequest) ProtoMessage() {}

func (x *GetAccountRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ledger_v1_ledger_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAccountRequest.ProtoReflect.Descriptor instead.
func (*GetAccountRequest) Descriptor() ([]byte, []int) {
	return file_proto_ledger_v1_ledger_proto_rawDescGZIP(), []int{5}
}

func (x *GetAccountRequest) GetId() []byte {
	if x != nil {
		return x.Id
	}
	return nil
}

type GetAccountResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Account       *Account               `protobuf:"bytes,1,opt,name=account,proto3" json:"account,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAccountResponse) Reset() {
	*x = GetAccountResponse{}
	mi := &file_proto_ledger_v1_ledger_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAccountResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAccountResponse) ProtoMessage() {}

func (x *GetAccountResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ledger_v1_ledger_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAccountResponse.ProtoReflect.Descriptor instead.
func (*GetAccountResponse) Descriptor() ([]byte, []int) {
	return file_proto_ledger_v1_ledger_proto_rawDescGZIP(), []int{6}
}

func (x *GetAccountResponse) GetAccount() *Account {
	if x != nil {
		return x.Account
	}
	return nil
}

type CreateTransferRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Id              []byte                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	DebitAccountId  []byte                 `protobuf:"bytes,2,opt,name=debit_account_id,json=debitAccountId,proto3" json:"debit_account_id,omitempty"`
	CreditAccountId []byte                 `protobuf:"bytes,3,opt,name=credit_account_id,json=creditAccountId,proto3" json:"credit_account_id,omitempty"`
	Amount          *Money                 `protobuf:"bytes,4,opt,name=amount,proto3" json:"amount,omitempty"`
	IdempotencyKey  []byte                 `protobuf:"bytes,5,opt,name=idempotency_key,json=idempotencyKey,proto3" json:"idempotency_key,omitempty"`
	Flags           uint32                 `protobuf:"varint,6,opt,name=flags,proto3" json:"flags,omitempty"`
	Timeout         uint64                 `protobuf:"varint,7,opt,name=timeout,proto3" json:"timeout,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *CreateTransferRequest) Reset() {
	*x = CreateTransferRequest{}
	mi := &file_proto_ledger_v1_ledger_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTransferRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTransferRequest) ProtoMessage() {}

func (x *CreateTransferRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ledger_v1_ledger_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTransferRequest.ProtoReflect.Descriptor instead.
func (*CreateTransferRequest) Descriptor() ([]byte, []int) {
	return file_proto_ledger_v1_ledger_proto_rawDescGZIP(), []int{7}
}

func (x *CreateTransferRequest) GetId() []byte {
	if x != nil {
		return x.Id
	}
	return nil
}

func (x *CreateTransferRequest) GetDebitAccountId() []byte {
	if x != nil {
		return x.DebitAccountId
	}
	return nil
}

func (x *CreateTransferRequest) GetCreditAccountId() []byte {
	if x != nil {
		return x.CreditAccountId
	}
	return nil
}

func (x *CreateTransferRequest) GetAmount() *Money {
	if x != nil {
		return x.Amount
	}
	return nil
}

func (x *CreateTransferRequest) GetIdempotencyKey() []byte {
	if x != nil {
		return x.IdempotencyKey
	}
	return nil
}

func (x *CreateTransferRequest) GetFlags() uint32 {
	if x != nil {
		return x.Flags
	}
	return 0
}

func (x *CreateTransferRequest) GetTimeout() uint64 {
	if x != nil {
		return x.Timeout
	}
	return 0
}

type CreateTransferResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Transfer      *Transfer              `protobuf:"bytes,1,opt,name=transfer,proto3" json:"transfer,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateTransferResponse) Reset() {
	*x = CreateTransferResponse{}
	mi := &file_proto_ledger_v1_ledger_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTransferResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTransferResponse) ProtoMessage() {}

func (x *CreateTransferResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ledger_v1_ledger_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTransferResponse.ProtoReflect.Descriptor instead.
func (*CreateTransferResponse) Descriptor() ([]byte, []int) {
	return file_proto_ledger_v1_ledger_proto_rawDescGZIP(), []int{8}
}

func (x *CreateTransferResponse) GetTransfer() *Transfer {
	if x != nil {
		return x.Transfer
	}
	return nil
}

// Batched API (D1.1): one RPC submits up to 8192 items and returns one
// positional result per item, mirroring TigerBeetle's batch protocol.
type TransferResult struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Ok    bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	// transfer is set when ok is true: the committed transfer.
	Transfer *Transfer `protobuf:"bytes,2,opt,name=transfer,proto3" json:"transfer,omitempty"`
	// error is set when ok is false: a human-readable per-item failure reason
	// (e.g. insufficient funds, unknown account).
	Error         string `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TransferResult) Reset() {
	*x = TransferResult{}
	mi := &file_proto_ledger_v1_ledger_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransferResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransferResult) ProtoMessage() {}

func (x *TransferResult) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ledger_v1_ledger_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransferResult.ProtoReflect.Descriptor instead.
func (*TransferResult) Descriptor() ([]byte, []int) {
	return file_proto_ledger_v1_ledger_proto_rawDescGZIP(), []int{9}
}

func (x *TransferResult) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *TransferResult) GetTransfer() *Transfer {
	if x != nil {
		return x.Transfer
	}
	return nil
}

func (x *TransferResult) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type CreateTransfersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Transfers     []*Transfer            `protobuf:"bytes,1,rep,name=transfers,proto3" json:"transfers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateTransfersRequest) Reset() {
	*x = CreateTransfersRequest{}
	mi := &file_proto_ledger_v1_ledger_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTransfersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTransfersRequest) ProtoMessage() {}

func (x *CreateTransfersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ledger_v1_ledger_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTransfersRequest.ProtoReflect.Descriptor instead.
func (*CreateTransfersRequest) Descriptor() ([]byte, []int) {
	return file_proto_ledger_v1_ledger_proto_rawDescGZIP(), []int{10}
}

func (x *CreateTransfersRequest) GetTransfers() []*Transfer {
	if x != nil {
		return x.Transfers
	}
	return nil
}

type CreateTransfersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Results       []*TransferResult      `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateTransfersResponse) Reset() {
	*x = CreateTransfersResponse{}
	mi := &file_proto_ledger_v1_ledger_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTransfersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTransfersResponse) ProtoMessage() {}

func (x *CreateTransfersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ledger_v1_ledger_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTransfersResponse.ProtoReflect.Descriptor instead.
func (*CreateTransfersResponse) Descriptor() ([]byte, []int) {
	return file_proto_ledger_v1_ledger_proto_rawDescGZIP(), []int{11}
}

func (x *CreateTransfersResponse) GetResults() []*TransferResult {
	if x != nil {
		return x.Results
	}
	return nil
}

type AccountResult struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Ok    bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	// account is set when ok is true: the created account.
	Account *Account `protobuf:"bytes,2,opt,name=account,proto3" json:"account,omitempty"`
	// error is set when ok is false.
	Error         string `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AccountResult) Reset() {
	*x = AccountResult{}
	mi := &file_proto_ledger_v1_ledger_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AccountResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AccountResult) ProtoMessage() {}

func (x *AccountResult) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ledger_v1_ledger_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AccountResult.ProtoReflect.Descriptor instead.
func (*AccountResult) Descriptor() ([]byte, []int) {
	return file_proto_ledger_v1_ledger_proto_rawDescGZIP(), []int{12}
}

func (x *AccountResult) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *AccountResult) GetAccount() *Account {
	if x != nil {
		return x.Account
	}
	return nil
}

func (x *AccountResult) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type CreateAccountsRequest struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	Accounts      []*CreateAccountRequest `protobuf:"bytes,1,rep,name=accounts,proto3" json:"accounts,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateAccountsRequest) Reset() {
	*x = CreateAccountsRequest{}
	mi := &file_proto_ledger_v1_ledger_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateAccountsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAccountsRequest) ProtoMessage() {}

func (x *CreateAccountsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ledger_v1_ledger_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAccountsRequest.ProtoReflect.Descriptor instead.
func (*CreateAccountsRequest) Descriptor() ([]byte, []int) {
	return file_proto_ledger_v1_ledger_proto_rawDescGZIP(), []int{13}
}

func (x *CreateAccountsRequest) GetAccounts() []*CreateAccountRequest {
	if x != nil {
		return x.Accounts
	}
	return nil
}

type CreateAccountsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Results       []*AccountResult       `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateAccountsResponse) Reset() {
	*x = CreateAccountsResponse{}
	mi := &file_proto_ledger_v1_ledger_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateAccountsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAccountsResponse) ProtoMessage() {}

func (x *CreateAccountsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ledger_v1_ledger_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAccountsResponse.ProtoReflect.Descriptor instead.
func (*CreateAccountsResponse) Descriptor() ([]byte, []int) {
	return file_proto_ledger_v1_ledger_proto_rawDescGZIP(), []int{14}
}

func (x *CreateAccountsResponse) GetResults() []*AccountResult {
	if x != nil {
		return x.Results
	}
	return nil
}

// Query API (D1.5): point-lookup for transfers and paginated transfer history
type GetTransferRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            []byte                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTransferRequest) Reset() {
	*x = GetTransferRequest{}
	mi := &file_proto_ledger_v1_ledger_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTransferRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTransferRequest) ProtoMessage() {}

func (x *GetTransferRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ledger_v1_ledger_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTransferRequest.ProtoReflect.Descriptor instead.
func (*GetTransferRequest) Descriptor() ([]byte, []int) {
	return file_proto_ledger_v1_ledger_proto_rawDescGZIP(), []int{15}
}

func (x *GetTransferRequest) GetId() []byte {
	if x != nil {
		return x.Id
	}
	return nil
}

type GetTransferResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Transfer      *Transfer              `protobuf:"bytes,1,opt,name=transfer,proto3" json:"transfer,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTransferResponse) Reset() {
	*x = GetTransferResponse{}
	mi := &file_proto_ledger_v1_ledger_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTransferResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTransferResponse) ProtoMessage() {}

func (x *GetTransferResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ledger_v1_ledger_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTransferResponse.ProtoReflect.Descriptor instead.
func (*GetTransferResponse) Descriptor() ([]byte, []int) {
	return file_proto_ledger_v1_ledger_proto_rawDescGZIP(), []int{16}
}

func (x *GetTransferResponse) GetTransfer() *Transfer {
	if x != nil {
		return x.Transfer
	}
	return nil
}

type GetAccountTransfersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccountId     []byte                 `protobuf:"bytes,1,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	AfterId       []byte                 `protobuf:"bytes,2,opt,name=after_id,json=afterId,proto3" json:"after_id,omitempty"`
	Limit         uint32                 `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAccountTransfersRequest) Reset() {
	*x = GetAccountTransfersRequest{}
	mi := &file_proto_ledger_v1_ledger_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAccountTransfersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAccountTransfersRequest) ProtoMessage() {}

func (x *GetAccountTransfersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ledger_v1_ledger_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAccountTransfersRequest.ProtoReflect.Descriptor instead.
func (*GetAccountTransfersRequest) Descriptor() ([]byte, []int) {
	return file_proto_ledger_v1_ledger_proto_rawDescGZIP(), []int{17}
}

func (x *GetAccountTransfersRequest) GetAccountId() []byte {
	if x != nil {
		return x.AccountId
	}
	return nil
}

func (x *GetAccountTransfersRequest) GetAfterId() []byte {
	if x != nil {
		return x.AfterId
	}
	return nil
}

func (x *GetAccountTransfersRequest) GetLimit() uint32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type GetAccountTransfersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Transfers     []*Transfer            `protobuf:"bytes,1,rep,name=transfers,proto3" json:"transfers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAccountTransfersResponse) Reset() {
	*x = GetAccountTransfersResponse{}
	mi := &file_proto_ledger_v1_ledger_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAccountTransfersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAccountTransfersResponse) ProtoMessage() {}

func (x *GetAccountTransfersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ledger_v1_ledger_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAccountTransfersResponse.ProtoReflect.Descriptor instead.
func (*GetAccountTransfersResponse) Descriptor() ([]byte, []int) {
	return file_proto_ledger_v1_ledger_proto_rawDescGZIP(), []int{18}
}

func (x *GetAccountTransfersResponse) GetTransfers() []*Transfer {
	if x != nil {
		return x.Transfers
	}
	return nil
}

var File_proto_ledger_v1_ledger_proto protoreflect.FileDescriptor

const file_proto_ledger_v1_ledger_proto_rawDesc = "" +
	"\n" +
	"\x1cproto/ledger/v1/ledger.proto\x12\tledger.v1\"'\n" +
	"\x05Money\x12\x0e\n" +
	"\x02lo\x18\x01 \x01(\x04R\x02lo\x12\x0e\n" +
	"\x02hi\x18\x02 \x01(\x04R\x02hi\"\x84\x03\n" +
	"\aAccount\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\fR\x02id\x12\x1a\n" +
	"\bcurrency\x18\x02 \x01(\tR\bcurrency\x125\n" +
	"\rposted_debits\x18\x03 \x01(\v2\x10.ledger.v1.MoneyR\fpostedDebits\x127\n" +
	"\x0eposted_credits\x18\x04 \x01(\v2\x10.ledger.v1.MoneyR\rpostedCredits\x127\n" +
	"\x0epending_debits\x18\x05 \x01(\v2\x10.ledger.v1.MoneyR\rpendingDebits\x129\n" +
	"\x0fpending_credits\x18\x06 \x01(\v2\x10.ledger.v1.MoneyR\x0ependingCredits\x12*\n" +
	"\abalance\x18\a \x01(\v2\x10.ledger.v1.MoneyR\abalance\x12=\n" +
	"\x11available_balance\x18\b \x01(\v2\x10.ledger.v1.MoneyR\x10availableBalance\"\x92\x02\n" +
	"\bTransfer\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\fR\x02id\x12(\n" +
	"\x10debit_account_id\x18\x02 \x01(\fR\x0edebitAccountId\x12*\n" +
	"\x11credit_account_id\x18\x03 \x01(\fR\x0fcreditAccountId\x12(\n" +
	"\x06amount\x18\x04 \x01(\v2\x10.ledger.v1.MoneyR\x06amount\x12'\n" +
	"\x0fidempotency_key\x18\x05 \x01(\fR\x0eidempotencyKey\x12\x1d\n" +
	"\n" +
	"created_at\x18\x06 \x01(\x03R\tcreatedAt\x12\x14\n" +
	"\x05flags\x18\a \x01(\rR\x05flags\x12\x18\n" +
	"\atimeout\x18\b \x01(\x04R\atimeout\"\x8a\x01\n" +
	"\x14CreateAccountRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\fR\x02id\x12\x1a\n" +
	"\bcurrency\x18\x02 \x01(\tR\bcurrency\x12F\n" +
	"\x16initial_posted_credits\x18\x03 \x01(\v2\x10.ledger.v1.MoneyR\x14initialPostedCredits\"E\n" +
	"\x15CreateAccountResponse\x12,\n" +
	"\aaccount\x18\x01 \x01(\v2\x12.ledger.v1.AccountR\aaccount\"#\n" +
	"\x11GetAccountRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\fR\x02id\"B\n" +
	"\x12GetAccountResponse\x12,\n" +
	"\aaccount\x18\x01 \x01(\v2\x12.ledger.v1.AccountR\aaccount\"\x80\x02\n" +
	"\x15CreateTransferRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\fR\x02id\x12(\n" +
	"\x10debit_account_id\x18\x02 \x01(\fR\x0edebitAccountId\x12*\n" +
	"\x11credit_account_id\x18\x03 \x01(\fR\x0fcreditAccountId\x12(\n" +
	"\x06amount\x18\x04 \x01(\v2\x10.ledger.v1.MoneyR\x06amount\x12'\n" +
	"\x0fidempotency_key\x18\x05 \x01(\fR\x0eidempotencyKey\x12\x14\n" +
	"\x05flags\x18\x06 \x01(\rR\x05flags\x12\x18\n" +
	"\atimeout\x18\a \x01(\x04R\atimeout\"I\n" +
	"\x16CreateTransferResponse\x12/\n" +
	"\btransfer\x18\x01 \x01(\v2\x13.ledger.v1.TransferR\btransfer\"g\n" +
	"\x0eTransferResult\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\x12/\n" +
	"\btransfer\x18\x02 \x01(\v2\x13.ledger.v1.TransferR\btransfer\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error\"K\n" +
	"\x16CreateTransfersRequest\x121\n" +
	"\ttransfers\x18\x01 \x03(\v2\x13.ledger.v1.TransferR\ttransfers\"N\n" +
	"\x17CreateTransfersResponse\x123\n" +
	"\aresults\x18\x01 \x03(\v2\x19.ledger.v1.TransferResultR\aresults\"c\n" +
	"\rAccountResult\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\x12,\n" +
	"\aaccount\x18\x02 \x01(\v2\x12.ledger.v1.AccountR\aaccount\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error\"T\n" +
	"\x15CreateAccountsRequest\x12;\n" +
	"\baccounts\x18\x01 \x03(\v2\x1f.ledger.v1.CreateAccountRequestR\baccounts\"L\n" +
	"\x16CreateAccountsResponse\x122\n" +
	"\aresults\x18\x01 \x03(\v2\x18.ledger.v1.AccountResultR\aresults\"$\n" +
	"\x12GetTransferRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\fR\x02id\"F\n" +
	"\x13GetTransferResponse\x12/\n" +
	"\btransfer\x18\x01 \x01(\v2\x13.ledger.v1.TransferR\btransfer\"l\n" +
	"\x1aGetAccountTransfersRequest\x12\x1d\n" +
	"\n" +
	"account_id\x18\x01 \x01(\fR\taccountId\x12\x19\n" +
	"\bafter_id\x18\x02 \x01(\fR\aafterId\x12\x14\n" +
	"\x05limit\x18\x03 \x01(\rR\x05limit\"P\n" +
	"\x1bGetAccountTransfersResponse\x121\n" +
	"\ttransfers\x18\x01 \x03(\v2\x13.ledger.v1.TransferR\ttransfers2\xea\x04\n" +
	"\rLedgerService\x12R\n" +
	"\rCreateAccount\x12\x1f.ledger.v1.CreateAccountRequest\x1a .ledger.v1.CreateAccountResponse\x12U\n" +
	"\x0eCreateAccounts\x12 .ledger.v1.CreateAccountsRequest\x1a!.ledger.v1.CreateAccountsResponse\x12I\n" +
	"\n" +
	"GetAccount\x12\x1c.ledger.v1.GetAccountRequest\x1a\x1d.ledger.v1.GetAccountResponse\x12U\n" +
	"\x0eCreateTransfer\x12 .ledger.v1.CreateTransferRequest\x1a!.ledger.v1.CreateTransferResponse\x12X\n" +
	"\x0fCreateTransfers\x12!.ledger.v1.CreateTransfersRequest\x1a\".ledger.v1.CreateTransfersResponse\x12L\n" +
	"\vGetTransfer\x12\x1d.ledger.v1.GetTransferRequest\x1a\x1e.ledger.v1.GetTransferResponse\x12d\n" +
	"\x13GetAccountTransfers\x12%.ledger.v1.GetAccountTransfersRequest\x1a&.ledger.v1.GetAccountTransfersResponseB*Z(aequitas-ledger/proto/ledger/v1;ledgerv1b\x06proto3"

var (
	file_proto_ledger_v1_ledger_proto_rawDescOnce sync.Once
	file_proto_ledger_v1_ledger_proto_rawDescData []byte
)

func file_proto_ledger_v1_ledger_proto_rawDescGZIP() []byte {
	file_proto_ledger_v1_ledger_proto_rawDescOnce.Do(func() {
		file_proto_ledger_v1_ledger_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_ledger_v1_ledger_proto_rawDesc), len(file_proto_ledger_v1_ledger_proto_rawDesc)))
	})
	return file_proto_ledger_v1_ledger_proto_rawDescData
}

var file_proto_ledger_v1_ledger_proto_msgTypes = make([]protoimpl.MessageInfo, 19)
var file_proto_ledger_v1_ledger_proto_goTypes = []any{
	(*Money)(nil),                       // 0: ledger.v1.Money
	(*Account)(nil),                     // 1: ledger.v1.Account
	(*Transfer)(nil),                    // 2: ledger.v1.Transfer
	(*CreateAccountRequest)(nil),        // 3: ledger.v1.CreateAccountRequest
	(*CreateAccountResponse)(nil),       // 4: ledger.v1.CreateAccountResponse
	(*GetAccountRequest)(nil),           // 5: ledger.v1.GetAccountRequest
	(*GetAccountResponse)(nil),          // 6: ledger.v1.GetAccountResponse
	(*CreateTransferRequest)(nil),       // 7: ledger.v1.CreateTransferRequest
	(*CreateTransferResponse)(nil),      // 8: ledger.v1.CreateTransferResponse
	(*TransferResult)(nil),              // 9: ledger.v1.TransferResult
	(*CreateTransfersRequest)(nil),      // 10: ledger.v1.CreateTransfersRequest
	(*CreateTransfersResponse)(nil),     // 11: ledger.v1.CreateTransfersResponse
	(*AccountResult)(nil),               // 12: ledger.v1.AccountResult
	(*CreateAccountsRequest)(nil),       // 13: ledger.v1.CreateAccountsRequest
	(*CreateAccountsResponse)(nil),      // 14: ledger.v1.CreateAccountsResponse
	(*GetTransferRequest)(nil),          // 15: ledger.v1.GetTransferRequest
	(*GetTransferResponse)(nil),         // 16: ledger.v1.GetTransferResponse
	(*GetAccountTransfersRequest)(nil),  // 17: ledger.v1.GetAccountTransfersRequest
	(*GetAccountTransfersResponse)(nil), // 18: ledger.v1.GetAccountTransfersResponse
}
var file_proto_ledger_v1_ledger_proto_depIdxs = []int32{
	0,  // 0: ledger.v1.Account.posted_debits:type_name -> ledger.v1.Money
	0,  // 1: ledger.v1.Account.posted_credits:type_name -> ledger.v1.Money
	0,  // 2: ledger.v1.Account.pending_debits:type_name -> ledger.v1.Money
	0,  // 3: ledger.v1.Account.pending_credits:type_name -> ledger.v1.Money
	0,  // 4: ledger.v1.Account.balance:type_name -> ledger.v1.Money
	0,  // 5: ledger.v1.Account.available_balance:type_name -> ledger.v1.Money
	0,  // 6: ledger.v1.Transfer.amount:type_name -> ledger.v1.Money
	0,  // 7: ledger.v1.CreateAccountRequest.initial_posted_credits:type_name -> ledger.v1.Money
	1,  // 8: ledger.v1.CreateAccountResponse.account:type_name -> ledger.v1.Account
	1,  // 9: ledger.v1.GetAccountResponse.account:type_name -> ledger.v1.Account
	0,  // 10: ledger.v1.CreateTransferRequest.amount:type_name -> ledger.v1.Money
	2,  // 11: ledger.v1.CreateTransferResponse.transfer:type_name -> ledger.v1.Transfer
	2,  // 12: ledger.v1.TransferResult.transfer:type_name -> ledger.v1.Transfer
	2,  // 13: ledger.v1.CreateTransfersRequest.transfers:type_name -> ledger.v1.Transfer
	9,  // 14: ledger.v1.CreateTransfersResponse.results:type_name -> ledger.v1.TransferResult
	1,  // 15: ledger.v1.AccountResult.account:type_name -> ledger.v1.Account
	3,  // 16: ledger.v1.CreateAccountsRequest.accounts:type_name -> ledger.v1.CreateAccountRequest
	12, // 17: ledger.v1.CreateAccountsResponse.results:type_name -> ledger.v1.AccountResult
	2,  // 18: ledger.v1.GetTransferResponse.transfer:type_name -> ledger.v1.Transfer
	2,  // 19: ledger.v1.GetAccountTransfersResponse.transfers:type_name -> ledger.v1.Transfer
	3,  // 20: ledger.v1.LedgerService.CreateAccount:input_type -> ledger.v1.CreateAccountRequest
	13, // 21: ledger.v1.LedgerService.CreateAccounts:input_type -> ledger.v1.CreateAccountsRequest
	5,  // 22: ledger.v1.LedgerService.GetAccount:input_type -> ledger.v1.GetAccountRequest
	7,  // 23: ledger.v1.LedgerService.CreateTransfer:input_type -> ledger.v1.CreateTransferRequest
	10, // 24: ledger.v1.LedgerService.CreateTransfers:input_type -> ledger.v1.CreateTransfersRequest
	15, // 25: ledger.v1.LedgerService.GetTransfer:input_type -> ledger.v1.GetTransferRequest
	17, // 26: ledger.v1.LedgerService.GetAccountTransfers:input_type -> ledger.v1.GetAccountTransfersRequest
	4,  // 27: ledger.v1.LedgerService.CreateAccount:output_type -> ledger.v1.CreateAccountResponse
	14, // 28: ledger.v1.LedgerService.CreateAccounts:output_type -> ledger.v1.CreateAccountsResponse
	6,  // 29: ledger.v1.LedgerService.GetAccount:output_type -> ledger.v1.GetAccountResponse
	8,  // 30: ledger.v1.LedgerService.CreateTransfer:output_type -> ledger.v1.CreateTransferResponse
	11, // 31: ledger.v1.LedgerService.CreateTransfers:output_type -> ledger.v1.CreateTransfersResponse
	16, // 32: ledger.v1.LedgerService.GetTransfer:output_type -> ledger.v1.GetTransferResponse
	18, // 33: ledger.v1.LedgerService.GetAccountTransfers:output_type -> ledger.v1.GetAccountTransfersResponse
	27, // [27:34] is the sub-list for method output_type
	20, // [20:27] is the sub-list for method input_type
	20, // [20:20] is the sub-list for extension type_name
	20, // [20:20] is the sub-list for extension extendee
	0,  // [0:20] is the sub-list for field type_name
}

func init() { file_proto_ledger_v1_ledger_proto_init() }
func file_proto_ledger_v1_ledger_proto_init() {
	if File_proto_ledger_v1_ledger_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_ledger_v1_ledger_proto_rawDesc), len(file_proto_ledger_v1_ledger_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   19,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_ledger_v1_ledger_proto_goTypes,
		DependencyIndexes: file_proto_ledger_v1_ledger_proto_depIdxs,
		MessageInfos:      file_proto_ledger_v1_ledger_proto_msgTypes,
	}.Build()
	File_proto_ledger_v1_ledger_proto = out.File
	file_proto_ledger_v1_ledger_proto_goTypes = nil
	file_proto_ledger_v1_ledger_proto_depIdxs = nil
}
