// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: proto/ledger/v1/ledger.proto

package ledgerv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Money represents 128-bit unsigned integer money amount using two uint64 fields.
type Money struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Lo            uint64                 `protobuf:"varint,1,opt,name=lo,proto3" json:"lo,omitempty"`
	Hi            uint64                 `protobuf:"varint,2,opt,name=hi,proto3" json:"hi,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Money) Reset() {
	*x = Money{}
	mi := &file_proto_ledger_v1_ledger_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Money) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Money) ProtoMessage() {}

func (x *Money) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ledger_v1_ledger_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Money.ProtoReflect.Descriptor instead.
func (*Money) Descriptor() ([]byte, []int) {
	return file_proto_ledger_v1_ledger_proto_rawDescGZIP(), []int{0}
}

func (x *Money) GetLo() uint64 {
	if x != nil {
		return x.Lo
	}
	return 0
}

func (x *Money) GetHi() uint64 {
	if x != nil {
		return x.Hi
	}
	return 0
}

type Account struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             []byte                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Currency       string                 `protobuf:"bytes,2,opt,name=currency,proto3" json:"currency,omitempty"`
	PostedDebits   *Money                 `protobuf:"bytes,3,opt,name=posted_debits,json=postedDebits,proto3" json:"posted_debits,omitempty"`
	PostedCredits  *Money                 `protobuf:"bytes,4,opt,name=posted_credits,json=postedCredits,proto3" json:"posted_credits,omitempty"`
	PendingDebits  *Money                 `protobuf:"bytes,5,opt,name=pending_debits,json=pendingDebits,proto3" json:"pending_debits,omitempty"`
	PendingCredits *Money                 `protobuf:"bytes,6,opt,name=pending_credits,json=pendingCredits,proto3" json:"pending_credits,omitempty"`
	Balance        *Money                 `protobuf:"bytes,7,opt,name=balance,proto3" json:"balance,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Account) Reset() {
	*x = Account{}
	mi := &file_proto_ledger_v1_ledger_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Account) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Account) ProtoMessage() {}

func (x *Account) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ledger_v1_ledger_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Account.ProtoReflect.Descriptor instead.
func (*Account) Descriptor() ([]byte, []int) {
	return file_proto_ledger_v1_ledger_proto_rawDescGZIP(), []int{1}
}

func (x *Account) GetId() []byte {
	if x != nil {
		return x.Id
	}
	return nil
}

func (x *Account) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *Account) GetPostedDebits() *Money {
	if x != nil {
		return x.PostedDebits
	}
	return nil
}

func (x *Account) GetPostedCredits() *Money {
	if x != nil {
		return x.PostedCredits
	}
	return nil
}

func (x *Account) GetPendingDebits() *Money {
	if x != nil {
		return x.PendingDebits
	}
	return nil
}

func (x *Account) GetPendingCredits() *Money {
	if x != nil {
		return x.PendingCredits
	}
	return nil
}

func (x *Account) GetBalance() *Money {
	if x != nil {
		return x.Balance
	}
	return nil
}

type Transfer struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Id              []byte                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	DebitAccountId  []byte                 `protobuf:"bytes,2,opt,name=debit_account_id,json=debitAccountId,proto3" json:"debit_account_id,omitempty"`
	CreditAccountId []byte                 `protobuf:"bytes,3,opt,name=credit_account_id,json=creditAccountId,proto3" json:"credit_account_id,omitempty"`
	Amount          *Money                 `protobuf:"bytes,4,opt,name=amount,proto3" json:"amount,omitempty"`
	IdempotencyKey  []byte                 `protobuf:"bytes,5,opt,name=idempotency_key,json=idempotencyKey,proto3" json:"idempotency_key,omitempty"`
	CreatedAt       int64                  `protobuf:"varint,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Transfer) Reset() {
	*x = Transfer{}
	mi := &file_proto_ledger_v1_ledger_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Transfer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Transfer) ProtoMessage() {}

func (x *Transfer) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ledger_v1_ledger_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Transfer.ProtoReflect.Descriptor instead.
func (*Transfer) Descriptor() ([]byte, []int) {
	return file_proto_ledger_v1_ledger_proto_rawDescGZIP(), []int{2}
}

func (x *Transfer) GetId() []byte {
	if x != nil {
		return x.Id
	}
	return nil
}

func (x *Transfer) GetDebitAccountId() []byte {
	if x != nil {
		return x.DebitAccountId
	}
	return nil
}

func (x *Transfer) GetCreditAccountId() []byte {
	if x != nil {
		return x.CreditAccountId
	}
	return nil
}

func (x *Transfer) GetAmount() *Money {
	if x != nil {
		return x.Amount
	}
	return nil
}

func (x *Transfer) GetIdempotencyKey() []byte {
	if x != nil {
		return x.IdempotencyKey
	}
	return nil
}

func (x *Transfer) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

type CreateAccountRequest struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	Id                   []byte                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Currency             string                 `protobuf:"bytes,2,opt,name=currency,proto3" json:"currency,omitempty"`
	InitialPostedCredits *Money                 `protobuf:"bytes,3,opt,name=initial_posted_credits,json=initialPostedCredits,proto3" json:"initial_posted_credits,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *CreateAccountRequest) Reset() {
	*x = CreateAccountRequest{}
	mi := &file_proto_ledger_v1_ledger_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateAccountRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAccountRequest) ProtoMessage() {}

func (x *CreateAccountRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ledger_v1_ledger_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAccountRequest.ProtoReflect.Descriptor instead.
func (*CreateAccountRequest) Descriptor() ([]byte, []int) {
	return file_proto_ledger_v1_ledger_proto_rawDescGZIP(), []int{3}
}

func (x *CreateAccountRequest) GetId() []byte {
	if x != nil {
		return x.Id
	}
	return nil
}

func (x *CreateAccountRequest) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *CreateAccountRequest) GetInitialPostedCredits() *Money {
	if x != nil {
		return x.InitialPostedCredits
	}
	return nil
}

type CreateAccountResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Account       *Account               `protobuf:"bytes,1,opt,name=account,proto3" json:"account,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateAccountResponse) Reset() {
	*x = CreateAccountResponse{}
	mi := &file_proto_ledger_v1_ledger_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateAccountResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAccountResponse) ProtoMessage() {}

func (x *CreateAccountResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ledger_v1_ledger_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAccountResponse.ProtoReflect.Descriptor instead.
func (*CreateAccountResponse) Descriptor() ([]byte, []int) {
	return file_proto_ledger_v1_ledger_proto_rawDescGZIP(), []int{4}
}

func (x *CreateAccountResponse) GetAccount() *Account {
	if x != nil {
		return x.Account
	}
	return nil
}

type GetAccountRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            []byte                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAccountRequest) Reset() {
	*x = GetAccountRequest{}
	mi := &file_proto_ledger_v1_ledger_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAccountRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAccountRequest) ProtoMessage() {}

func (x *GetAccountRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ledger_v1_ledger_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAccountRequest.ProtoReflect.Descriptor instead.
func (*GetAccountRequest) Descriptor() ([]byte, []int) {
	return file_proto_ledger_v1_ledger_proto_rawDescGZIP(), []int{5}
}

func (x *GetAccountRequest) GetId() []byte {
	if x != nil {
		return x.Id
	}
	return nil
}

type GetAccountResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Account       *Account               `protobuf:"bytes,1,opt,name=account,proto3" json:"account,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAccountResponse) Reset() {
	*x = GetAccountResponse{}
	mi := &file_proto_ledger_v1_ledger_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAccountResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAccountResponse) ProtoMessage() {}

func (x *GetAccountResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ledger_v1_ledger_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAccountResponse.ProtoReflect.Descriptor instead.
func (*GetAccountResponse) Descriptor() ([]byte, []int) {
	return file_proto_ledger_v1_ledger_proto_rawDescGZIP(), []int{6}
}

func (x *GetAccountResponse) GetAccount() *Account {
	if x != nil {
		return x.Account
	}
	return nil
}

type CreateTransferRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Id              []byte                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	DebitAccountId  []byte                 `protobuf:"bytes,2,opt,name=debit_account_id,json=debitAccountId,proto3" json:"debit_account_id,omitempty"`
	CreditAccountId []byte                 `protobuf:"bytes,3,opt,name=credit_account_id,json=creditAccountId,proto3" json:"credit_account_id,omitempty"`
	Amount          *Money                 `protobuf:"bytes,4,opt,name=amount,proto3" json:"amount,omitempty"`
	IdempotencyKey  []byte                 `protobuf:"bytes,5,opt,name=idempotency_key,json=idempotencyKey,proto3" json:"idempotency_key,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *CreateTransferRequest) Reset() {
	*x = CreateTransferRequest{}
	mi := &file_proto_ledger_v1_ledger_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTransferRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTransferRequest) ProtoMessage() {}

func (x *CreateTransferRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ledger_v1_ledger_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTransferRequest.ProtoReflect.Descriptor instead.
func (*CreateTransferRequest) Descriptor() ([]byte, []int) {
	return file_proto_ledger_v1_ledger_proto_rawDescGZIP(), []int{7}
}

func (x *CreateTransferRequest) GetId() []byte {
	if x != nil {
		return x.Id
	}
	return nil
}

func (x *CreateTransferRequest) GetDebitAccountId() []byte {
	if x != nil {
		return x.DebitAccountId
	}
	return nil
}

func (x *CreateTransferRequest) GetCreditAccountId() []byte {
	if x != nil {
		return x.CreditAccountId
	}
	return nil
}

func (x *CreateTransferRequest) GetAmount() *Money {
	if x != nil {
		return x.Amount
	}
	return nil
}

func (x *CreateTransferRequest) GetIdempotencyKey() []byte {
	if x != nil {
		return x.IdempotencyKey
	}
	return nil
}

type CreateTransferResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Transfer      *Transfer              `protobuf:"bytes,1,opt,name=transfer,proto3" json:"transfer,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateTransferResponse) Reset() {
	*x = CreateTransferResponse{}
	mi := &file_proto_ledger_v1_ledger_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTransferResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTransferResponse) ProtoMessage() {}

func (x *CreateTransferResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ledger_v1_ledger_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTransferResponse.ProtoReflect.Descriptor instead.
func (*CreateTransferResponse) Descriptor() ([]byte, []int) {
	return file_proto_ledger_v1_ledger_proto_rawDescGZIP(), []int{8}
}

func (x *CreateTransferResponse) GetTransfer() *Transfer {
	if x != nil {
		return x.Transfer
	}
	return nil
}

var File_proto_ledger_v1_ledger_proto protoreflect.FileDescriptor

const file_proto_ledger_v1_ledger_proto_rawDesc = "" +
	"\n" +
	"\x1cproto/ledger/v1/ledger.proto\x12\tledger.v1\"'\n" +
	"\x05Money\x12\x0e\n" +
	"\x02lo\x18\x01 \x01(\x04R\x02lo\x12\x0e\n" +
	"\x02hi\x18\x02 \x01(\x04R\x02hi\"\xc5\x02\n" +
	"\aAccount\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\fR\x02id\x12\x1a\n" +
	"\bcurrency\x18\x02 \x01(\tR\bcurrency\x125\n" +
	"\rposted_debits\x18\x03 \x01(\v2\x10.ledger.v1.MoneyR\fpostedDebits\x127\n" +
	"\x0eposted_credits\x18\x04 \x01(\v2\x10.ledger.v1.MoneyR\rpostedCredits\x127\n" +
	"\x0epending_debits\x18\x05 \x01(\v2\x10.ledger.v1.MoneyR\rpendingDebits\x129\n" +
	"\x0fpending_credits\x18\x06 \x01(\v2\x10.ledger.v1.MoneyR\x0ependingCredits\x12*\n" +
	"\abalance\x18\a \x01(\v2\x10.ledger.v1.MoneyR\abalance\"\xe2\x01\n" +
	"\bTransfer\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\fR\x02id\x12(\n" +
	"\x10debit_account_id\x18\x02 \x01(\fR\x0edebitAccountId\x12*\n" +
	"\x11credit_account_id\x18\x03 \x01(\fR\x0fcreditAccountId\x12(\n" +
	"\x06amount\x18\x04 \x01(\v2\x10.ledger.v1.MoneyR\x06amount\x12'\n" +
	"\x0fidempotency_key\x18\x05 \x01(\fR\x0eidempotencyKey\x12\x1d\n" +
	"\n" +
	"created_at\x18\x06 \x01(\x03R\tcreatedAt\"\x8a\x01\n" +
	"\x14CreateAccountRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\fR\x02id\x12\x1a\n" +
	"\bcurrency\x18\x02 \x01(\tR\bcurrency\x12F\n" +
	"\x16initial_posted_credits\x18\x03 \x01(\v2\x10.ledger.v1.MoneyR\x14initialPostedCredits\"E\n" +
	"\x15CreateAccountResponse\x12,\n" +
	"\aaccount\x18\x01 \x01(\v2\x12.ledger.v1.AccountR\aaccount\"#\n" +
	"\x11GetAccountRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\fR\x02id\"B\n" +
	"\x12GetAccountResponse\x12,\n" +
	"\aaccount\x18\x01 \x01(\v2\x12.ledger.v1.AccountR\aaccount\"\xd0\x01\n" +
	"\x15CreateTransferRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\fR\x02id\x12(\n" +
	"\x10debit_account_id\x18\x02 \x01(\fR\x0edebitAccountId\x12*\n" +
	"\x11credit_account_id\x18\x03 \x01(\fR\x0fcreditAccountId\x12(\n" +
	"\x06amount\x18\x04 \x01(\v2\x10.ledger.v1.MoneyR\x06amount\x12'\n" +
	"\x0fidempotency_key\x18\x05 \x01(\fR\x0eidempotencyKey\"I\n" +
	"\x16CreateTransferResponse\x12/\n" +
	"\btransfer\x18\x01 \x01(\v2\x13.ledger.v1.TransferR\btransfer2\x85\x02\n" +
	"\rLedgerService\x12R\n" +
	"\rCreateAccount\x12\x1f.ledger.v1.CreateAccountRequest\x1a .ledger.v1.CreateAccountResponse\x12I\n" +
	"\n" +
	"GetAccount\x12\x1c.ledger.v1.GetAccountRequest\x1a\x1d.ledger.v1.GetAccountResponse\x12U\n" +
	"\x0eCreateTransfer\x12 .ledger.v1.CreateTransferRequest\x1a!.ledger.v1.CreateTransferResponseB*Z(aequitas-ledger/proto/ledger/v1;ledgerv1b\x06proto3"

var (
	file_proto_ledger_v1_ledger_proto_rawDescOnce sync.Once
	file_proto_ledger_v1_ledger_proto_rawDescData []byte
)

func file_proto_ledger_v1_ledger_proto_rawDescGZIP() []byte {
	file_proto_ledger_v1_ledger_proto_rawDescOnce.Do(func() {
		file_proto_ledger_v1_ledger_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_ledger_v1_ledger_proto_rawDesc), len(file_proto_ledger_v1_ledger_proto_rawDesc)))
	})
	return file_proto_ledger_v1_ledger_proto_rawDescData
}

var file_proto_ledger_v1_ledger_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_proto_ledger_v1_ledger_proto_goTypes = []any{
	(*Money)(nil),                  // 0: ledger.v1.Money
	(*Account)(nil),                // 1: ledger.v1.Account
	(*Transfer)(nil),               // 2: ledger.v1.Transfer
	(*CreateAccountRequest)(nil),   // 3: ledger.v1.CreateAccountRequest
	(*CreateAccountResponse)(nil),  // 4: ledger.v1.CreateAccountResponse
	(*GetAccountRequest)(nil),      // 5: ledger.v1.GetAccountRequest
	(*GetAccountResponse)(nil),     // 6: ledger.v1.GetAccountResponse
	(*CreateTransferRequest)(nil),  // 7: ledger.v1.CreateTransferRequest
	(*CreateTransferResponse)(nil), // 8: ledger.v1.CreateTransferResponse
}
var file_proto_ledger_v1_ledger_proto_depIdxs = []int32{
	0,  // 0: ledger.v1.Account.posted_debits:type_name -> ledger.v1.Money
	0,  // 1: ledger.v1.Account.posted_credits:type_name -> ledger.v1.Money
	0,  // 2: ledger.v1.Account.pending_debits:type_name -> ledger.v1.Money
	0,  // 3: ledger.v1.Account.pending_credits:type_name -> ledger.v1.Money
	0,  // 4: ledger.v1.Account.balance:type_name -> ledger.v1.Money
	0,  // 5: ledger.v1.Transfer.amount:type_name -> ledger.v1.Money
	0,  // 6: ledger.v1.CreateAccountRequest.initial_posted_credits:type_name -> ledger.v1.Money
	1,  // 7: ledger.v1.CreateAccountResponse.account:type_name -> ledger.v1.Account
	1,  // 8: ledger.v1.GetAccountResponse.account:type_name -> ledger.v1.Account
	0,  // 9: ledger.v1.CreateTransferRequest.amount:type_name -> ledger.v1.Money
	2,  // 10: ledger.v1.CreateTransferResponse.transfer:type_name -> ledger.v1.Transfer
	3,  // 11: ledger.v1.LedgerService.CreateAccount:input_type -> ledger.v1.CreateAccountRequest
	5,  // 12: ledger.v1.LedgerService.GetAccount:input_type -> ledger.v1.GetAccountRequest
	7,  // 13: ledger.v1.LedgerService.CreateTransfer:input_type -> ledger.v1.CreateTransferRequest
	4,  // 14: ledger.v1.LedgerService.CreateAccount:output_type -> ledger.v1.CreateAccountResponse
	6,  // 15: ledger.v1.LedgerService.GetAccount:output_type -> ledger.v1.GetAccountResponse
	8,  // 16: ledger.v1.LedgerService.CreateTransfer:output_type -> ledger.v1.CreateTransferResponse
	14, // [14:17] is the sub-list for method output_type
	11, // [11:14] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_proto_ledger_v1_ledger_proto_init() }
func file_proto_ledger_v1_ledger_proto_init() {
	if File_proto_ledger_v1_ledger_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_ledger_v1_ledger_proto_rawDesc), len(file_proto_ledger_v1_ledger_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_ledger_v1_ledger_proto_goTypes,
		DependencyIndexes: file_proto_ledger_v1_ledger_proto_depIdxs,
		MessageInfos:      file_proto_ledger_v1_ledger_proto_msgTypes,
	}.Build()
	File_proto_ledger_v1_ledger_proto = out.File
	file_proto_ledger_v1_ledger_proto_goTypes = nil
	file_proto_ledger_v1_ledger_proto_depIdxs = nil
}
